### PR TITLE
Apply ORCID linking pattern

### PR DESCRIPTION
**Pull request by ajnelson-nist**
This one-liner presents a pattern for discussion.

Signed-off-by: Alex Nelson <alexander.nelson@nist.gov>

### CODE REVIEW

**Comment by bdietz** [comment]
what about linking the ORCID instead?

**Comment by ajnelson-nist** [comment]
I thought I did?  Could you show the Markdown you mean?  Here's my result:

```markdown
 - [Alex Nelson](https://orcid.org/0000-0002-3771-570X), National Institute of Standards and Technology
```

**Comment by bdietz** [comment]
I was thinking more like this:

`- Alex Nelson, National Institute of Standards and Technology[(ORCID: 0000-0002-3771-570X)](https://orcid.org/0000-0002-3771-570X)`

My reasoning was that someone might not know what to expect w/ a linked name. My assumption, as a user, is that it would go to a person's organizational staff page, rather than their ORCID page. I would prefer to make the link label more explicit.

**Comment by ajnelson-nist** [comment]
Oh, I see now.  I mostly agree, will push one tweak for parentheses.

**Comment by ajnelson-nist** [comment]
Format adjusted, to hyperlink just the identifier, and undo the "ATM Machine" grammar note.

**Comment by bdietz** [comment]
Looks good. I figure I'll merge this when we're ready to link everyone's IDs. Is that OK with you?

**Comment by ajnelson-nist** [comment]
Sounds good to me.  Thanks!

**Pull request merged**
